### ISSUE TITLE
K8s Cluster Pod Fails To Create 

### ISSUE THREAD

**Issue by apooniajjn** [nuagenetworks/nuage-kubernetes#98]
# K8s POD creation Failure Due to Expired Cert 

## Problem Statement 

While following the official Nuage kubernetes Integration guide. My k8s cluster stops creating any new POD and throws an error for cert expired. To resolve this I had to regenerate 
certificate. 

## Logs Output 

All my pods are stuck at ContainerCreating state as per statement. If you look for detailed output, it shows cert error. 

```
[root@master ~]# kubectl get pods
NAME                     READY     STATUS              RESTARTS   AGE
nginx-3599678771-h4jhm   0/1       ContainerCreating   0          12s
nginx-3599678771-rqvwj   0/1       ContainerCreating   0          12s
nginx-3599678771-vm9t8   0/1       ContainerCreating   0          12s
nginx-node02             0/1       ContainerCreating   0          15m
[root@master ~]# kubectl describe pod nginx-3599678771-h4jhm
Name:		nginx-3599678771-h4jhm
Namespace:	default
Node:		minion02.nuage.lab/10.0.0.15
Start Time:	Thu, 09 Nov 2017 23:22:56 +0000
Labels:		app=nginx
		pod-template-hash=3599678771
Status:		Pending
IP:
Controllers:	ReplicaSet/nginx-3599678771
Containers:
  nginx:
    Container ID:
    Image:		nginx:1.9.1
    Image ID:
    Port:		80/TCP
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xqpd8 (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  default-token-xqpd8:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-xqpd8
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----				-------------	--------	------		-------
  25s		25s		1	{default-scheduler }				Normal		Scheduled	Successfully assigned nginx-3599678771-h4jhm to minion02.nuage.lab
  18s		6s		2	{kubelet minion02.nuage.lab}			Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "nginx-3599678771-h4jhm_default" with SetupNetworkError: "Failed to setup network for pod \"nginx-3599678771-h4jhm_default(eafc7fbc-c5a4-11e7-8b00-fa163e3565a7)\" using network plugins \"vsp-k8s\": exit status 1; Skipping pod"
```

Output from **/var/log/messages** file 
```
Starting recovery of all containers
Nov  9 22:37:47 master kubelet: I1109 22:37:47.335739     442 kubelet_node_status.go:204] Setting node annotation to enable volume controller attach/detach
Nov  9 22:37:47 master kubelet: I1109 22:37:47.352947     442 kubelet_node_status.go:74] Attempting to register node master.nuage.lab
Nov  9 22:37:47 master kubelet: I1109 22:37:47.386626     442 kubelet_node_status.go:113] Node master.nuage.lab was previously registered
Nov  9 22:37:47 master kubelet: I1109 22:37:47.386658     442 kubelet_node_status.go:77] Successfully registered node master.nuage.lab
Nov  9 22:37:47 master kubelet: I1109 22:37:47.858466     442 manager.go:293] Recovery completed
Nov  9 22:37:49 master nuagekubemon: 2017/11/09 22:37:49 server.go:2161: http: TLS handshake error from 10.0.0.14:38649: remote error: expired certificate
Nov  9 22:37:50 master nuagekubemon: 2017/11/09 22:37:50 server.go:2161: http: TLS handshake error from 10.0.0.15:41525: remote error: expired certificate
Nov  9 22:37:51 master nuagekubemon: 2017/11/09 22:37:51 server.go:2161: http: TLS handshake error from 10.0.0.14:38651: remote error: expired certificate
```

Output from K8s Node throwing cert error. 
```
Nov 10 01:01:15 minion01 kernel: XFS (dm-4): Mounting V4 Filesystem
Nov 10 01:01:15 minion01 kernel: XFS (dm-4): Ending clean mount
Nov 10 01:01:15 minion01 journal: Nov 10 01:01:15|5|vsp-k8s|ERR|[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
Nov 10 01:01:15 minion01 journal: Nov 10 01:01:15|6|vsp-k8s|ERR|Traceback (most recent call last):#012  File "/usr/libexec/kubernetes/kubelet-plugins/net/exec/vsp-k8s/vsp-k8s", line 844, in main#012    nuage_trigger(options, config)#012  File "/usr/libexec/kubernetes/kubelet-plugins/net/exec/vsp-k8s/vsp-k8s", line 608, in nuage_trigger#012    hook(options, config)#012  File "/usr/libexec/kubernetes/kubelet-plugins/net/exec/vsp-k8s/vsp-k8s", line 652, in setup#012    pod_hook(options, config, True)#012  File "/usr/libexec/kubernetes/kubelet-plugins/net/exec/vsp-k8s/vsp-k8s", line 664, in pod_hook#012    metadata = find_metadata(options, config, setup)#012  File "/usr/libexec/kubernetes/kubelet-plugins/net/exec/vsp-k8s/vsp-k8s", line 415, in find_metadata#012    timeout=5#012  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 507, in post#012    return self.request('POST', url, data=data, json=json, **kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request#012    resp = self.send(prep, **send_kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send#012    r = adapter.send(request, **kwargs)#012  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 431, in send#012    raise SSLError(e, request=request)#012SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
Nov 10 01:01:15 minion01 journal: Nov 10 01:01:15|7|vsp-k8s|ERR|Nuage VSP exec plugin cannot be executed
```

## Suggested Solution 

Nuagekubmon service certificate created by ansible task expires after 60 days to renew the certificate so pod creation doesn't fail due to that. Please follow below method to renew the certificate on your k8s cluster. 

1. Login to your Kubernetes MASTER
2. Change your working directory to **/root/nuage-kubernetes/manual-installation**
3. Update the gencerts.sh file to allow expiration date by adding **-days 10000** value on your openssl command as below
   ```
   openssl req -new -x509 -key $REST_CA_KEY -out $REST_CA_CERT -days 10000 -subj "/CN=nuage-signer"
   ```
4. Save the **gencerts.sh** file
5. Run the script as **./gencerts.sh --output-cert-dir=/root/** which will create self signed certs and paste it your root directory location
6. Copy your nuageMonCA.crt, nuageMonServer.crt, nuageMonServer.key to **/usr/share/nuagekubemon/** directory and replace the old certs (You can save the old certs in your desired location if needed)
  ```
  cd /root
  mv nuageMonCA.crt nuageMonServer.crt nuageMonServer.key /usr/share/nuagekubemon/
  ```
7. You will need to copy your client cert, client key and CA cert to your each Kubernetes Minion as well
8. You can do that from your master host using scp command to **/usr/share/vsp-k8s/** directory as below (Do it for every Kubernetes Minion)
  ```
  scp nuageMonCA.crt nuageMonClient.crt     nuageMonClient.key root@<minion_node>:/usr/share/vsp-k8s/
  ```
9. Restart Service **systemctl restart nuagekubemon** on your Kubernetes MASTER
10. Restart Service **systemctl restart kubelet.service** on your each Kubernetes Minion

## Expected Result 

Expected result is as per below. 

```
[root@master ~]# kubectl get pods
NAME           READY     STATUS    RESTARTS   AGE
nginx-node01   1/1       Running   0          1h
[root@master ~]#
[root@master ~]#
[root@master ~]# kubectl describe pod nginx-node01
Name:		nginx-node01
Namespace:	default
Node:		minion01.nuage.lab/10.0.0.14
Start Time:	Fri, 10 Nov 2017 01:22:39 +0000
Labels:		env=test
Status:		Running
IP:		70.70.0.55
Controllers:	<none>
Containers:
  nginx:
    Container ID:	docker://c381bced1a963779fca21b02eddeb32ae95d3716ef6b5d49faf6bccfb2aaf43e
    Image:		nginx
    Image ID:		docker-pullable://docker.io/nginx@sha256:9fca103a62af6db7f188ac3376c60927db41f88b8d2354bf02d2290a672dc425
    Port:
    State:		Running
      Started:		Fri, 10 Nov 2017 01:22:42 +0000
    Ready:		True
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-xqpd8 (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True
  Ready 	True
  PodScheduled 	True
Volumes:
  default-token-xqpd8:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-xqpd8
QoS Class:	BestEffort
Tolerations:	<none>
No events.
[root@master ~]#
```

**Comment by rparulek** [comment]
@apooniajjn I see that you are using "vsp-k8s" which is exec plugin and has been deprecated by Nuage starting Nuage VSP 4.0.10 I think. What version of kubernetes and Nuage VSP are you using? We have now moved to using CNI plugin for resolving k8s pods in place of exec plugin. Please refer to the latest open sourced Nuage Kubernetes documentation for more specifics.

**Comment by apooniajjn** [comment]
@rparulek I am using 4.0.8 and k8s as v1.5.4 ..

**Comment by rparulek** [comment]
Can you try the new CNi plugin with Nuage 4.0.10?

**Comment by apooniajjn** [comment]
@rparulek my current setup s for 4.0R8 but if I plan to test/upgrade it on 4.0R10 i will use the new plugin. But to make it work on 4.0R8,  I had to renew certificate.
